### ISSUE TITLE
Add a `py.typed` marker file

### ISSUE THREAD

**Issue by mattmess1221** [Zaczero/starlette-compress#1]
By default, mypy requires all imported packages to contains a `py.typed` marker file to tell it the package has type hints.

**Comment by Zaczero** [comment]
No problem, added in 1.2.1 :+1:

**Comment by mattmess1221** [comment]
This is still broken. The `py.typed` file is not included in the wheel or sdist.

```console
➜  starlette-compress git:(main) unzip -l dist/*.whl
Archive:  dist/starlette_compress-1.5.0-py3-none-any.whl
  Length      Date    Time    Name
---------  ---------- -----   ----
    17626  02-02-2020 00:00   starlette_compress/__init__.py
     3925  02-02-2020 00:00   starlette_compress-1.5.0.dist-info/METADATA
       87  02-02-2020 00:00   starlette_compress-1.5.0.dist-info/WHEEL
      632  02-02-2020 00:00   starlette_compress-1.5.0.dist-info/licenses/LICENSE
      434  02-02-2020 00:00   starlette_compress-1.5.0.dist-info/RECORD
---------                     -------
    22704                     5 files
➜  starlette-compress git:(main) tar -tf dist/*.tar.gz
starlette_compress-1.5.0/starlette_compress/__init__.py
starlette_compress-1.5.0/.gitignore
starlette_compress-1.5.0/LICENSE
starlette_compress-1.5.0/README.md
starlette_compress-1.5.0/pyproject.toml
starlette_compress-1.5.0/PKG-INFO
```

This is likely because the hatch configuration is only including py files.
Relevant config:
https://github.com/Zaczero/starlette-compress/blob/b5846afd64d67e67538e720784e068325dcda658/pyproject.toml#L60-L61

That table isn't really needed for this project. Hatch is smart enough to know what should be in the wheel as long as your package name matches the import, which yours does. If it didn't, an error message would recommend adding a table similar to this.

```toml
[tool.hatch.build.targets.wheel]
packages = ["foo"]
```
